# Generated by Django 4.1.4 on 2022-12-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfomace_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
