# Generated by Django 4.1.4 on 2022-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_user_perfomace_index_alter_user_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfomace_index',
            field=models.CharField(default='0%', max_length=4),
        ),
    ]
